### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by arcoyk** [ckreibich/scholar.py#69]
The result is empty now. I've confirmed the results have been ok about a week ago. I've also checked it with different network. Google Scholar may has been updated.

**Comment by eknoes** [comment]
What is your query? For me it works without any changes, can not verify the described behaviour

**Comment by patrickallo** [comment]
I have a similar issue: empty results even with the example-queries. Haven't been able to fix it, but it seems that the `send_query` method of `ScholarQuerier` ends up with None (leading to `return`) instead of parsing the html.

**Comment by samerabdo** [comment]
No result obtain for citation with bt or en 

scholar.py -c 1 --author "albert einstein" --phrase "quantum theory" --citation bt
no error message, but empty result.

the ordinary command without citation work.
scholar.py -c 1 --author "albert einstein" --phrase "quantum theory"

I think the problem in adjusting "google setting" thought python.

I have suggestion about bibtex citation, it will be greatful and also easy to extract information from "import into BibTex" by making python script goes directly to link "import into BibTex"

thanks

**Comment by Babababanana** [comment]
I have the same problem.

scholar.py -c 1 --author "albert einstein" --phrase "quantum theory"
It even worked 1 h ago, and suddenly stopped working after I added the paging function and tried to print the results.

**Comment by falematte** [comment]
I have the same problem!

**Comment by ckreibich** [comment]
Hi folks, when you see a `HTTP Error 503: Service Unavailable` (when using debugging output, e.g. with -ddd) then it means that the server didn't like the response. There are two possible reasons: scholar.py has become outdated and no longer accepts the query, or you've exceeded Google's acceptable rate limit. The former happens relatively rarely (thank you Google!). You can find out whether the latter is to blame by running the same query from a different IP address, if you have one available.

Also, always use the --cookie-file option to specify a cookie textfile. Just say `--cookie-file ~/.scholar-cookies.txt` or some such. This makes your set of queries appear more browser-like, and reduces the query rate limit problem for me.

I don't think there's an actual bug here, so please let me close this.

**Comment by jiequancui** [comment]
Hi,

Thanks for your work!
How can I get a cookie file when I use the --cookie-file?

Best,
